# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcbolt < Formula
  desc "Modern Xcode CLI + TUI"
  homepage "https://github.com/vburojevic/xcbolt"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/vburojevic/xcbolt/releases/download/v0.1.2/xcbolt_0.1.2_darwin_amd64.tar.gz"
    sha256 "0650c10f1f8eaf9a82500068a2dc2ed75288887701fcf438e3d329814e04c378"

    def install
      bin.install "xcbolt"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/vburojevic/xcbolt/releases/download/v0.1.2/xcbolt_0.1.2_darwin_arm64.tar.gz"
    sha256 "81581f431e9bd9059dd5ca6211510a25d763eadbc3b6ea68fe8e95fce49b79a3"

    def install
      bin.install "xcbolt"
    end
  end

  test do
    system "#{bin}/xcbolt", "--help"
  end
end
